{
 "title": "00000006-0100-0015-0000-000000000002",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "W phsB (mag)",
   "type": "timeseries",
   "description": "MeterReadingProfile.mapping.meterReading.readingMMXU.W.phsB.cVal.mag",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", w_phsb_mag FROM data WHERE device_uuid = '00000006-0100-0015-0000-000000000002'"
    }
   ]
  },
  {
   "title": "Corriente Batería",
   "type": "timeseries",
   "description": "MeterReadingProfile.mapping.meterReading.readingMMXU.VAr.neut.cVal.mag",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", var_neut_mag FROM data WHERE device_uuid = '00000006-0100-0015-0000-000000000002' ORDER BY timestamp DESC LIMIT 200"
    }
   ]
  },
  {
   "title": "Estado de Carga Batería",
   "type": "timeseries",
   "description": "MeterReadingProfile.mapping.meterReading.readingMMXU.VAr.phsB.cVal.mag",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", var_phsb_mag FROM data WHERE device_uuid = '00000006-0100-0015-0000-000000000002' ORDER BY timestamp ASC LIMIT 200"
    }
   ]
  },
  {
   "title": "Voltaje Batería",
   "type": "timeseries",
   "description": "MeterReadingProfile.mapping.meterReading.readingMMXU.VAr.net.cVal.mag",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", var_net_mag FROM data WHERE device_uuid = '00000006-0100-0015-0000-000000000002' ORDER BY timestamp ASC LIMIT 200"
    }
   ]
  }
 ]
}