{
 "title": "00000001-0005-0020-0000-000000000001",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Corriente Media",
   "type": "timeseries",
   "description": "MeterReadingProfile.mapping.meterReading.readingMMXU.A.phsB.cVal.mag",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", a_phsb_mag FROM data WHERE device_uuid = '00000001-0005-0020-0000-000000000001'"
    }
   ]
  },
  {
   "title": "Potencia Activa Total",
   "type": "timeseries",
   "description": "MeterReadingProfile.mapping.meterReading.readingMMXU.PhV.phsC.cVal.mag",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", phv_phsc_mag FROM data WHERE device_uuid = '00000001-0005-0020-0000-000000000001'"
    }
   ]
  },
  {
   "title": "Voltaje Medio L-N",
   "type": "timeseries",
   "description": "MeterReadingProfile.mapping.meterReading.readingMMXU.PhV.net.cVal.mag",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", phv_net_mag FROM data WHERE device_uuid = '00000001-0005-0020-0000-000000000001'"
    }
   ]
  },
  {
   "title": "Potencia Aparente Total",
   "type": "timeseries",
   "description": "MeterReadingProfile.mapping.meterReading.readingMMXU.PPV.phsBC.cVal.mag",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", ppv_phsbc_mag FROM data WHERE device_uuid = '00000001-0005-0020-0000-000000000001'"
    }
   ]
  },
  {
   "title": "Factor de Potencia",
   "type": "timeseries",
   "description": "MeterReadingProfile.mapping.meterReading.readingMMXU.PPV.phsCA.cVal.mag",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", ppv_phsca_mag FROM data WHERE device_uuid = '00000001-0005-0020-0000-000000000001'"
    }
   ]
  },
  {
   "title": "Frecuencia",
   "type": "timeseries",
   "description": "MeterReadingProfile.mapping.meterReading.readingMMXU.VA.net.cVal.mag",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", va_net_mag FROM data WHERE device_uuid = '00000001-0005-0020-0000-000000000001'"
    }
   ]
  }
 ]
}