{
 "title": "00000003-0001-0005-0000-000000000001",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperatura",
   "type": "timeseries",
   "description": "MeterReadingProfile.mapping.meterReading.readingMMXU.A.neut.cVal.mag",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", a_neut_mag FROM data WHERE device_uuid = '00000003-0001-0005-0000-000000000001'"
    }
   ]
  },
  {
   "title": "Tiltangle",
   "type": "timeseries",
   "description": "MeterReadingProfile.mapping.meterReading.readingMMXU.A.phsB.cVal.mag",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", a_phsb_mag FROM data WHERE device_uuid = '00000003-0001-0005-0000-000000000001'"
    }
   ]
  },
  {
   "title": "Irradiancia",
   "type": "timeseries",
   "description": "MeterReadingProfile.mapping.meterReading.readingMMXU.A.net.cVal.mag",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", a_net_mag FROM data WHERE device_uuid = '00000003-0001-0005-0000-000000000001'"
    }
   ]
  }
 ]
}