{
 "title": "p_PERSEO_Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Pyranometer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Irradianza",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "targets": [
    {
     "dataset": "openfmb",
     "rawSql": "select \"timestamp\", a_net_mag as \"Irradianza\"\nfrom data\nwhere device_uuid = '00000003-0001-0005-0000-000000000001' AND $__timeFilter(\"timestamp\")\nORDER BY \"timestamp\" ASC;"
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select \"timestamp\", a_neut_mag as \"Temperatura\"\r\nfrom data\r\nwhere device_uuid = '00000003-0001-0005-0000-000000000001' AND $__timeFilter(\"timestamp\")\r\nORDER BY \"timestamp\" ASC;"
    }
   ]
  },
  {
   "title": "Angulo Y",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "select \"timestamp\", a_phsc_mag as \"Angulo Y\"\r\nfrom data\r\nwhere device_uuid = '00000003-0001-0005-0000-000000000001' AND $__timeFilter(\"timestamp\")\r\nORDER BY \"timestamp\" ASC;"
    }
   ]
  },
  { "title": "Inversor Quattro - Baterías", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Temperatura",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \"timestamp\", a_neut_mag\r\nfrom data\r\nwhere device_uuid = '00000003-0001-0005-0000-000000000001' AND $__timeFilter(\"timestamp\")\r\nORDER BY \"timestamp\" ASC;"
    }
   ]
  },
  {
   "title": "Angulo X",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "select \"timestamp\", a_phsb_mag as \"Angulo X\"\r\nfrom data\r\nwhere device_uuid = '00000003-0001-0005-0000-000000000001' AND $__timeFilter(\"timestamp\")\r\nORDER BY \"timestamp\" ASC;"
    }
   ]
  },
  {
   "title": "POWER",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "dataset": "openfmb",
     "rawSql": "select \"timestamp\", var_phsa_mag as \"Active\"\nfrom data\nwhere device_uuid = '00000006-0100-0015-0000-000000000002' AND $__timeFilter(\"timestamp\")\nORDER BY \"timestamp\" ASC;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \"timestamp\", var_phsc_mag as \"Battery State\"\r\nfrom data\r\nwhere device_uuid = '00000006-0100-0015-0000-000000000002' AND $__timeFilter(\"timestamp\")\r\nORDER BY \"timestamp\" ASC;"
    }
   ]
  },
  {
   "title": "VOLTAGE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "select \"timestamp\", var_net_mag as \"Voltage\"\r\nfrom public.data\r\nwhere device_uuid = '00000006-0100-0015-0000-000000000002' AND $__timeFilter(\"timestamp\")\r\nORDER BY \"timestamp\" ASC;"
    }
   ]
  },
  {
   "title": "Porcentaje de carga",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \"timestamp\", var_phsb_mag\r\nfrom data\r\nwhere device_uuid = '00000006-0100-0015-0000-000000000002' AND $__timeFilter(\"timestamp\")\r\nORDER BY \"timestamp\" ASC;"
    }
   ]
  },
  {
   "title": "Meter - PEL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "POWER",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 10, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "dataset": "openfmb",
       "rawSql": "select \"timestamp\", phv_phsc_mag as \"Active\", ppv_phsab_mag as \"Reactive\", ppv_phsbc_mag as \"Aparent\"\nfrom data\nwhere device_uuid = '00000001-0006-0020-0000-000000000001' AND $__timeFilter(\"timestamp\")\nORDER BY \"timestamp\" ASC;"
      }
     ]
    },
    {
     "title": "ENERGY",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 10, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  SUM(phv_phsc_mag) / ((COUNT(phv_phsc_mag) * 3600.0) / (($__to - $__from) / 1000.0))\r\nFROM \r\n  data\r\nWHERE \r\n  timestamp >= $__timeFrom() and timestamp <= $__timeTo() and device_uuid = '00000001-0006-0020-0000-000000000001';"
      }
     ]
    },
    {
     "title": "CURRENT",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "rawSql": "select \"timestamp\", a_net_mag as \"Current L1\", a_neut_mag as \"Current L2\", a_phsa_mag as \"Current L3\", \"a_phsb_mag\" as \"Current Avg.\"\r\nfrom data\r\nwhere device_uuid = '00000001-0006-0020-0000-000000000001' AND $__timeFilter(\"timestamp\")\r\nORDER BY \"timestamp\" ASC;"
      }
     ]
    },
    {
     "title": "FREQUENCY",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 10, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "select \"timestamp\", va_net_mag\r\nfrom data\r\nwhere device_uuid = '00000001-0006-0020-0000-000000000001' AND $__timeFilter(\"timestamp\")\r\nORDER BY \"timestamp\" ASC;"
      }
     ]
    },
    {
     "title": "VOLTAGE",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "rawSql": "select \"timestamp\", pf_phsa_mag as \"Voltage L1N\", pf_phsb_mag as \"Voltage L2N\", pf_phsc_mag as \"Voltage L3N\", phv_net_mag as \"Voltage L-N Avg.\"\r\nfrom public.data\r\nwhere device_uuid = '00000001-0006-0020-0000-000000000001' AND $__timeFilter(\"timestamp\")\r\nORDER BY \"timestamp\" ASC;"
      }
     ]
    }
   ]
  },
  {
   "title": "Meter - Fronius",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "POWER",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 10, "x": 0, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "dataset": "openfmb",
       "rawSql": "select \"timestamp\", phv_phsc_mag as \"Active\", ppv_phsab_mag as \"Reactive\", ppv_phsbc_mag as \"Aparent\"\nfrom data\nwhere device_uuid = '00000001-0005-0020-0000-000000000001' AND $__timeFilter(\"timestamp\")\nORDER BY \"timestamp\" ASC;"
      }
     ]
    },
    {
     "title": "FREQUENCY",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 10, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "select \"timestamp\", va_net_mag\r\nfrom data\r\nwhere device_uuid = '00000001-0005-0020-0000-000000000001' AND $__timeFilter(\"timestamp\")\r\nORDER BY \"timestamp\" ASC;"
      }
     ]
    },
    {
     "title": "CURRENT",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "rawSql": "select \"timestamp\", a_net_mag as \"Current L1\", a_neut_mag as \"Current L2\", a_phsa_mag as \"Current L3\", \"a_phsb_mag\" as \"Current Avg.\"\r\nfrom data\r\nwhere device_uuid = '00000001-0005-0020-0000-000000000001' AND $__timeFilter(\"timestamp\")\r\nORDER BY \"timestamp\" ASC;"
      }
     ]
    },
    {
     "title": "ENERGY",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 10, "y": 177 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  SUM(phv_phsc_mag) / ((COUNT(phv_phsc_mag) * 3600.0) / (($__to - $__from) / 1000.0))\r\nFROM \r\n  data\r\nWHERE \r\n  timestamp >= $__timeFrom() and timestamp <= $__timeTo() and device_uuid = '00000001-0005-0020-0000-000000000001';"
      }
     ]
    },
    {
     "title": "VOLTAGE",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 177 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "rawSql": "select \"timestamp\", pf_phsa_mag as \"Voltage L1N\", pf_phsb_mag as \"Voltage L2N\", pf_phsc_mag as \"Voltage L3N\", phv_net_mag as \"Voltage L-N Avg.\"\r\nfrom public.data\r\nwhere device_uuid = '00000001-0005-0020-0000-000000000001' AND $__timeFilter(\"timestamp\")\r\nORDER BY \"timestamp\" ASC;"
      }
     ]
    }
   ]
  },
  {
   "title": "Meter - Microinversores",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "POWER",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 10, "x": 0, "y": 171 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "dataset": "openfmb",
       "rawSql": "select \"timestamp\", phv_phsc_mag as \"Active\", ppv_phsab_mag as \"Reactive\", ppv_phsbc_mag as \"Aparent\"\nfrom data\nwhere device_uuid = '00000001-0003-0020-0000-000000000001' AND $__timeFilter(\"timestamp\")\nORDER BY \"timestamp\" ASC;"
      }
     ]
    },
    {
     "title": "ENERGY",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 10, "y": 171 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  SUM(phv_phsc_mag) / ((COUNT(phv_phsc_mag) * 3600.0) / (($__to - $__from) / 1000.0))\r\nFROM \r\n  data\r\nWHERE \r\n  timestamp >= $__timeFrom() and timestamp <= $__timeTo() and device_uuid = '00000001-0003-0020-0000-000000000001';"
      }
     ]
    },
    {
     "title": "CURRENT",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 171 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "rawSql": "select \"timestamp\", a_net_mag as \"Current L1\", a_neut_mag as \"Current L2\", a_phsa_mag as \"Current L3\", \"a_phsb_mag\" as \"Current Avg.\"\r\nfrom data\r\nwhere device_uuid = '00000001-0003-0020-0000-000000000001' AND $__timeFilter(\"timestamp\")\r\nORDER BY \"timestamp\" ASC;"
      }
     ]
    },
    {
     "title": "FREQUENCY",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 10, "y": 178 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "select \"timestamp\", va_net_mag\r\nfrom data\r\nwhere device_uuid = '00000001-0003-0020-0000-000000000001' AND $__timeFilter(\"timestamp\")\r\nORDER BY \"timestamp\" ASC;"
      }
     ]
    },
    {
     "title": "VOLTAGE",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 178 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "rawSql": "select \"timestamp\", pf_phsa_mag as \"Voltage L1N\", pf_phsb_mag as \"Voltage L2N\", pf_phsc_mag as \"Voltage L3N\", phv_net_mag as \"Voltage L-N Avg.\"\r\nfrom public.data\r\nwhere device_uuid = '00000001-0003-0020-0000-000000000001' AND $__timeFilter(\"timestamp\")\r\nORDER BY \"timestamp\" ASC;"
      }
     ]
    }
   ]
  },
  {
   "title": "Meter - Iluminación",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "POWER",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 10, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "kwatt" } },
     "targets": [
      {
       "dataset": "openfmb",
       "rawSql": "select \"timestamp\", phv_phsc_mag as \"Active\", ppv_phsab_mag as \"Reactive\", ppv_phsbc_mag as \"Aparent\"\nfrom data\nwhere device_uuid = '00000001-0001-0020-0000-000000000001' AND $__timeFilter(\"timestamp\")\nORDER BY \"timestamp\" ASC;"
      }
     ]
    },
    {
     "title": "ENERGY",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 10, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  SUM(phv_phsc_mag) / ((COUNT(phv_phsc_mag) * 3600.0) / (($__to - $__from) / 1000.0))\r\nFROM \r\n  data\r\nWHERE \r\n  timestamp >= $__timeFrom() and timestamp <= $__timeTo() and device_uuid = '00000001-0001-0020-0000-000000000001';"
      }
     ]
    },
    {
     "title": "CURRENT",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "rawSql": "select \"timestamp\", a_net_mag as \"Current L1\", a_neut_mag as \"Current L2\", a_phsa_mag as \"Current L3\", \"a_phsb_mag\" as \"Current Avg.\"\r\nfrom data\r\nwhere device_uuid = '00000001-0001-0020-0000-000000000001' AND $__timeFilter(\"timestamp\")\r\nORDER BY \"timestamp\" ASC;"
      }
     ]
    },
    {
     "title": "FREQUENCY",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 10, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "select \"timestamp\", va_net_mag\r\nfrom data \r\nwhere device_uuid = '00000001-0001-0020-0000-000000000001' AND $__timeFilter(\"timestamp\")\r\nORDER BY \"timestamp\" ASC;"
      }
     ]
    },
    {
     "title": "VOLTAGE",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "rawSql": "select \"timestamp\", pf_phsa_mag as \"Voltage L1N\", pf_phsb_mag as \"Voltage L2N\", pf_phsc_mag as \"Voltage L3N\", phv_net_mag as \"Voltage L-N Avg.\"\r\nfrom public.data\r\nwhere device_uuid = '00000001-0001-0020-0000-000000000001' AND $__timeFilter(\"timestamp\")\r\nORDER BY \"timestamp\" ASC;"
      }
     ]
    }
   ]
  },
  {
   "title": "Meter - Operador de Red",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "POWER",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 10, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "dataset": "openfmb",
       "rawSql": "select \"timestamp\", phv_phsc_mag as \"Active\", ppv_phsab_mag as \"Reactive\", ppv_phsbc_mag as \"Aparent\"\nfrom data\nwhere device_uuid = '00000001-0002-0020-0000-000000000001' AND $__timeFilter(\"timestamp\")\nORDER BY \"timestamp\" ASC;"
      }
     ]
    },
    {
     "title": "ENERGY",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 10, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  SUM(phv_phsc_mag) / ((COUNT(phv_phsc_mag) * 3600.0) / (($__to - $__from) / 1000.0))\r\nFROM \r\n  data\r\nWHERE \r\n  timestamp >= $__timeFrom() and timestamp <= $__timeTo() and device_uuid = '00000001-0002-0020-0000-000000000001';"
      }
     ]
    },
    {
     "title": "CURRENT",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "rawSql": "select \"timestamp\", a_net_mag as \"Current L1\", a_neut_mag as \"Current L2\", a_phsa_mag as \"Current L3\", \"a_phsb_mag\" as \"Current Avg.\"\r\nfrom data\r\nwhere device_uuid = '00000001-0002-0020-0000-000000000001' AND $__timeFilter(\"timestamp\")\r\nORDER BY \"timestamp\" ASC;"
      }
     ]
    },
    {
     "title": "FREQUENCY",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 10, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "select \"timestamp\", va_net_mag\r\nfrom data\r\nwhere device_uuid = '00000001-0002-0020-0000-000000000001' AND $__timeFilter(\"timestamp\")\r\nORDER BY \"timestamp\" ASC;"
      }
     ]
    },
    {
     "title": "VOLTAGE",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "rawSql": "select \"timestamp\", pf_phsa_mag as \"Voltage L1N\", pf_phsb_mag as \"Voltage L2N\", pf_phsc_mag as \"Voltage L3N\", phv_net_mag as \"Voltage L-N Avg.\"\r\nfrom public.data\r\nwhere device_uuid = '00000001-0002-0020-0000-000000000001' AND $__timeFilter(\"timestamp\")\r\nORDER BY \"timestamp\" ASC;"
      }
     ]
    }
   ]
  },
  {
   "title": "Meter - Medidor Inversor Quattro",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "POWER",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 10, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "dataset": "openfmb",
       "rawSql": "select \"timestamp\", phv_phsc_mag as \"Active\", ppv_phsab_mag as \"Reactive\", ppv_phsbc_mag as \"Aparent\"\nfrom data\nwhere device_uuid = '00000001-0004-0020-0000-000000000001' AND $__timeFilter(\"timestamp\")\nORDER BY \"timestamp\" ASC;"
      }
     ]
    },
    {
     "title": "ENERGY",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 10, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  SUM(phv_phsc_mag) / ((COUNT(phv_phsc_mag) * 3600.0) / (($__to - $__from) / 1000.0))\r\nFROM \r\n  data\r\nWHERE \r\n  timestamp >= $__timeFrom() and timestamp <= $__timeTo() and device_uuid = '00000001-0004-0020-0000-000000000001';"
      }
     ]
    },
    {
     "title": "CURRENT",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "rawSql": "select \"timestamp\", a_net_mag as \"Current L1\", a_neut_mag as \"Current L2\", a_phsa_mag as \"Current L3\", \"a_phsb_mag\" as \"Current Avg.\"\r\nfrom data\r\nwhere device_uuid = '00000001-0004-0020-0000-000000000001' AND $__timeFilter(\"timestamp\")\r\nORDER BY \"timestamp\" ASC;"
      }
     ]
    },
    {
     "title": "FREQUENCY",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 10, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "select \"timestamp\", va_net_mag\r\nfrom data\r\nwhere device_uuid = '00000001-0004-0020-0000-000000000001' AND $__timeFilter(\"timestamp\")\r\nORDER BY \"timestamp\" ASC;"
      }
     ]
    },
    {
     "title": "VOLTAGE",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "rawSql": "select \"timestamp\", pf_phsa_mag as \"Voltage L1N\", pf_phsb_mag as \"Voltage L2N\", pf_phsc_mag as \"Voltage L3N\", phv_net_mag as \"Voltage L-N Avg.\"\r\nfrom public.data\r\nwhere device_uuid = '00000001-0004-0020-0000-000000000001' AND $__timeFilter(\"timestamp\")\r\nORDER BY \"timestamp\" ASC;"
      }
     ]
    }
   ]
  }
 ]
}